// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit by hand.
// The fixed module surface the deck transpiler resolves imports against.
import * as React from 'react'
import * as ReactDOM from 'react-dom'
import * as ReactDOMClient from 'react-dom/client'
import * as FramerMotion from 'framer-motion'
import * as _deck_Annotator from '../deck-template/src/deck/Annotator'
import * as _deck_Build from '../deck-template/src/deck/Build'
import * as _deck_Deck from '../deck-template/src/deck/Deck'
import * as _deck_DeckContext from '../deck-template/src/deck/DeckContext'
import * as _deck_Reveal from '../deck-template/src/deck/Reveal'
import * as _deck_Slide from '../deck-template/src/deck/Slide'
import * as _deck_icons from '../deck-template/src/deck/icons'
import * as _deck_useInView from '../deck-template/src/deck/useInView'
import * as _components_Accordion from '../deck-template/src/components/Accordion'
import * as _components_Agenda from '../deck-template/src/components/Agenda'
import * as _components_Bento from '../deck-template/src/components/Bento'
import * as _components_BigNumber from '../deck-template/src/components/BigNumber'
import * as _components_BrowserFrame from '../deck-template/src/components/BrowserFrame'
import * as _components_Charts from '../deck-template/src/components/Charts'
import * as _components_Chat from '../deck-template/src/components/Chat'
import * as _components_CodeWindow from '../deck-template/src/components/CodeWindow'
import * as _components_Comparison from '../deck-template/src/components/Comparison'
import * as _components_Contrast from '../deck-template/src/components/Contrast'
import * as _components_CountUp from '../deck-template/src/components/CountUp'
import * as _components_Cover from '../deck-template/src/components/Cover'
import * as _components_Globe from '../deck-template/src/components/Globe'
import * as _components_Marquee from '../deck-template/src/components/Marquee'
import * as _components_Pricing from '../deck-template/src/components/Pricing'
import * as _components_Quote from '../deck-template/src/components/Quote'
import * as _components_Section from '../deck-template/src/components/Section'
import * as _components_Split from '../deck-template/src/components/Split'
import * as _components_SpotlightCard from '../deck-template/src/components/SpotlightCard'
import * as _components_StatGrid from '../deck-template/src/components/StatGrid'
import * as _components_Steps from '../deck-template/src/components/Steps'
import * as _components_Table from '../deck-template/src/components/Table'
import * as _components_Tabs from '../deck-template/src/components/Tabs'
import * as _components_Team from '../deck-template/src/components/Team'
import * as _components_TiltCard from '../deck-template/src/components/TiltCard'
import * as _components_Timeline from '../deck-template/src/components/Timeline'
import * as _components_VisualDashboard from '../deck-template/src/components/VisualDashboard'

// Normalize a module to a CJS-interop shape (Sucrase emits require()-based code).
const wrap = (m: Record<string, unknown>) => ({ __esModule: true, ...m, default: m?.default ?? m })

export const registry: Record<string, unknown> = {
  react: wrap(React),
  'react-dom': wrap(ReactDOM),
  'react-dom/client': wrap(ReactDOMClient),
  'framer-motion': wrap(FramerMotion),
  './deck/Annotator': wrap(_deck_Annotator),
  './deck/Build': wrap(_deck_Build),
  './deck/Deck': wrap(_deck_Deck),
  './deck/DeckContext': wrap(_deck_DeckContext),
  './deck/Reveal': wrap(_deck_Reveal),
  './deck/Slide': wrap(_deck_Slide),
  './deck/icons': wrap(_deck_icons),
  './deck/useInView': wrap(_deck_useInView),
  './components/Accordion': wrap(_components_Accordion),
  './components/Agenda': wrap(_components_Agenda),
  './components/Bento': wrap(_components_Bento),
  './components/BigNumber': wrap(_components_BigNumber),
  './components/BrowserFrame': wrap(_components_BrowserFrame),
  './components/Charts': wrap(_components_Charts),
  './components/Chat': wrap(_components_Chat),
  './components/CodeWindow': wrap(_components_CodeWindow),
  './components/Comparison': wrap(_components_Comparison),
  './components/Contrast': wrap(_components_Contrast),
  './components/CountUp': wrap(_components_CountUp),
  './components/Cover': wrap(_components_Cover),
  './components/Globe': wrap(_components_Globe),
  './components/Marquee': wrap(_components_Marquee),
  './components/Pricing': wrap(_components_Pricing),
  './components/Quote': wrap(_components_Quote),
  './components/Section': wrap(_components_Section),
  './components/Split': wrap(_components_Split),
  './components/SpotlightCard': wrap(_components_SpotlightCard),
  './components/StatGrid': wrap(_components_StatGrid),
  './components/Steps': wrap(_components_Steps),
  './components/Table': wrap(_components_Table),
  './components/Tabs': wrap(_components_Tabs),
  './components/Team': wrap(_components_Team),
  './components/TiltCard': wrap(_components_TiltCard),
  './components/Timeline': wrap(_components_Timeline),
  './components/VisualDashboard': wrap(_components_VisualDashboard),
}
