package main

import (
	"strings"
	"unicode"
)

// cannedDeck builds a valid, presentable deck from the prompt without any LLM.
// It is used when ANTHROPIC_API_KEY is unset so the whole app is demoable.
func cannedDeck(prompt string) string {
	topic := cleanTopic(prompt)
	if topic == "" {
		topic = "Your Idea"
	}
	title := topic
	if len(title) > 48 {
		title = strings.TrimSpace(title[:48])
	}

	// Never tell a visitor to edit server/.env — on a hosted deployment they have
	// no shell. The BYOK form in Settings is the one action that actually works
	// for them, and it takes effect on the very next generation.
	msg := "This is a sample deck on " + topic +
		" — a fixed template, not AI-authored. Add your own API key in Settings to generate a real deck from your prompt."

	app := strings.ReplaceAll(cannedAppTemplate, "{{TOPIC}}", topic)

	var b strings.Builder
	b.WriteString(msg)
	b.WriteString("\nTITLE: ")
	b.WriteString(title)
	b.WriteString("\n\n```css title=tokens.css\n")
	b.WriteString(tokensDefaultCSS)
	b.WriteString("\n```\n\n```tsx title=App.tsx\n")
	b.WriteString(app)
	b.WriteString("\n```\n")
	return b.String()
}

// cleanTopic keeps letters, numbers, spaces and light punctuation from the prompt.
func cleanTopic(s string) string {
	s = strings.TrimSpace(s)
	// drop a leading "create/build/make a deck about" style preamble
	lower := strings.ToLower(s)
	for _, p := range []string{"create a pitch deck for", "create a pitch deck about",
		"a pitch deck for", "a pitch deck about", "pitch deck for", "pitch deck about",
		"create a deck about", "build a deck about", "make a deck about",
		"a deck about", "deck about", "create a presentation about", "presentation about",
		"create a deck for", "build a deck for", "a deck for", "deck for",
		"pitch for", "pitch"} {
		if strings.HasPrefix(lower, p) {
			s = strings.TrimSpace(s[len(p):])
			break
		}
	}
	var out strings.Builder
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsNumber(r) || unicode.IsSpace(r) ||
			strings.ContainsRune("-–—&.,:'", r) {
			out.WriteRune(r)
		}
	}
	res := strings.Join(strings.Fields(out.String()), " ")
	if res == "" {
		return res
	}
	// capitalize first letter for a title-ish feel
	r := []rune(res)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

const cannedAppTemplate = `import Deck from './deck/Deck';
import Slide from './deck/Slide';
import Build from './deck/Build';
import Reveal from './deck/Reveal';
import Cover from './components/Cover';
import Agenda from './components/Agenda';
import Contrast from './components/Contrast';
import Split from './components/Split';
import StatGrid from './components/StatGrid';
import CountUp from './components/CountUp';
import BigNumber from './components/BigNumber';
import Section from './components/Section';
import Steps from './components/Steps';
import Quote from './components/Quote';
import TiltCard from './components/TiltCard';
import VisualDashboard from './components/VisualDashboard';

const panel = (extra = 0.22): React.CSSProperties => ({
  position: 'absolute',
  inset: 0,
  background: ` + "`radial-gradient(120% 100% at 30% 20%, color-mix(in srgb, var(--primary) ${extra * 100}%, transparent), transparent 60%), var(--surface-2)`" + `,
});

export default function App() {
  return (
    <Deck>
      <Cover
        nav="Cover"
        kicker="Cue AI"
        title={<span className="accent-text">{{TOPIC}}</span>}
        subtitle="A live, responsive deck — every slide is a working web page."
        foot="Generated by Cue"
      />

      <Slide center nav="Thesis" notes="Set up the core idea, then reveal the payoff.">
        <h2 className="headline" style={{ fontSize: 'clamp(34px,5.5vw,68px)', marginInline: 'auto' }}>
          The idea is simple.{' '}
          <span className="accent-text">The impact isn't.</span>
        </h2>
        <Build at={1}>
          <p className="subhead" style={{ marginTop: 20 }}>
            {{TOPIC}} — reimagined as something you can actually see and use.
          </p>
        </Build>
      </Slide>

      <Agenda
        nav="Agenda"
        kicker="Agenda"
        title="What we'll cover."
        items={[
          'The problem',
          'How it works',
          'Why it matters',
          { title: 'What comes next', hint: '2 min' },
        ]}
      />

      <Contrast
        nav="The problem"
        kicker="The shift"
        title="From effort to answers."
        left={{
          label: 'Before',
          title: 'The old way',
          points: [
            'Slow and manual',
            'Hard to share',
            'Static and lifeless',
          ],
        }}
        right={{
          label: 'With {{TOPIC}}',
          title: 'The new way',
          points: [
            'Instant and automatic',
            'A link, not a file',
            'Live, interactive, real',
          ],
        }}
      />

      <Split
        nav="How it works"
        kicker="How it works"
        title={<>Everything, <span className="accent-text">in one place.</span></>}
        body="A single surface that turns your idea into a working, responsive experience."
        media={
          <>
            <div style={panel(0.22)} />
            <div style={{ position: 'relative', padding: 'clamp(14px,3vw,40px)', width: '100%', display: 'flex', justifyContent: 'center' }}>
              <TiltCard>
                <VisualDashboard />
              </TiltCard>
            </div>
          </>
        }
      />

      <StatGrid
        nav="Proof"
        kicker="Why it matters"
        title="Numbers that compound."
        stats={[
          { value: <CountUp to={10} suffix="x" />, label: 'Faster', caption: 'idea to output' },
          { value: <CountUp to={100} suffix="%" />, label: 'Responsive', caption: 'any screen, any size' },
          { value: <CountUp to={0} />, label: 'Files to email', caption: 'just share a link' },
        ]}
      />

      <BigNumber
        nav="Big number"
        kicker="The takeaway"
        value={<CountUp to={1} />}
        caption="prompt is all it takes."
        foot="From idea to a live deck"
      />

      <Section
        nav="Part two"
        n={2}
        kicker="Part two"
        title={<>Where this <span className="accent-text">goes.</span></>}
      />

      <Steps
        nav="Next"
        kicker="What's next"
        title="Three steps forward."
        items={[
          { title: 'Prompt', body: 'Describe your idea in a sentence.' },
          { title: 'Generate', body: 'Cue builds a live, responsive deck.' },
          { title: 'Present', body: 'Share a link and present from anywhere.' },
        ]}
      />

      <Quote
        nav="Quote"
        text="Slides should be as alive as the ideas inside them."
        name="Cue AI"
        role="Presentation decks that are working web apps"
      />

      <Slide center nav="Close" notes="Make the ask.">
        <Reveal>
          <h2 className="display" style={{ fontSize: 'clamp(40px,7vw,96px)' }}>
            <span className="accent-text">Just tell Cue.</span>
          </h2>
          <p className="subhead" style={{ marginTop: 16 }}>
            One prompt in — a deck out.
          </p>
        </Reveal>
      </Slide>
    </Deck>
  );
}
`
